ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Overview
This project showcases how to use Spring to support multiple API versions using content negotiation. I wanted to keep each version implementation in its own package, minimizing the need for using fully qualified names. To emphasize the isolation, I used identical names is each version, so no FooV1 vs FooV2 DTOs.

== Implementation
One interesting aspect of the code is that the same resource, `/some-resource`, has its implementation spread across two classes, one for each version. Spring classpath scanning will complain about duplicate bean names, which is easily remedied by providing one, e.g. `@RestController("v2.SomeResource")`.

== Prerequisites
* JDK 21 or greater

== Building
`./mvnw clean install` - to build and run the tests
`./mvnw spring-boot:run` - to start the application

== Installation
Being a showcase project, there is nothing to install.

== Tips and Tricks

From IDEA, you can run the HTTP requests in `ContentNegotiationApplication.http` after you have launched the application.

== Troubleshooting


== License and Credits
* This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].