ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Overview
This project showcases how to use Spring to support multiple API versions using content negotiation. I wanted to keep each version implementation in its own package, minimizing the need for using fully qualified names. To emphasize the isolation, I used identical names is each version, so no FooV1 vs FooV2 DTOs.

== Implementation
Structurizr supports only a single workspace at a time, encouraging us to launch different views depending on the audience.  We'll make use of  https://docs.structurizr.com/dsl/cookbook/workspace-extension/[Workspace extension] and the ideas expressed in https://docs.structurizr.com/usage/enterprise[Enterprise scenario]. The goal is to maintain an enterprise view of the systems while still keeping the modeling local to each team.  In this example, we have two teams, one in Boston and one in Los Angeles, maintaining the systems. We'll maintain three workspaces:
1. a landscape workspace that models all the systems and their relations ships, maintained by the architecture team
1. a system workspace, maintained by each team, showing the details of each service and their relationships

== Prerequisites
* JDK 21 or greater

== Building
`./mvnw clean install` - to build and run the tests
`./mvnw spring-boot:run` - to start the application

== Installation
Being a showcase project, there is nothing to install.

== Tips and Tricks

From IDEA, you can run the HTTP requests in `ContentNegotiationApplication.http` after you have launched the application.

== Troubleshooting


== License and Credits
* This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].